"""empty message

Revision ID: 39a2f08551ef
Revises: 
Create Date: 2023-06-21 12:07:21.133792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a2f08551ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('housekeepers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=82), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rooms',
    sa.Column('number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('number'),
     # Add this line
    )

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.Integer(), sa.ForeignKey('rooms.number'), nullable=False),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_name', sa.String(length=128), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_name'], ['housekeepers.name'], ),
    sa.ForeignKeyConstraint(['room_number'], ['rooms.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('rooms')
    op.drop_table('housekeepers')
    op.drop_table('guests')
    # ### end Alembic commands ###
